name: Deploy Storybook

on:
  push:
    branches:
      - main # Trigger the workflow only when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build Storybook
      - name: Build Storybook
        run: bun run build-storybook # Make sure you have the script in your package.json

      # Deploy to GitHub Pages
      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_branch: gh-pages # The branch to deploy to
          folder: storybook-static # Default folder for Storybook build
          personal_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token to authenticate
